"""Builds the static read-only demo in demo/ from one saved scan: `uv run python scripts/build_demo.py [scan.json]`.

With no argument it uses the newest VIRTUAL 30d scan in data/whales/. The scan is stripped of anything local
(saved file path, timing) and checked for keys and paths before it is written. demo/demo.js is assembled from
web/whales.js (the same render code as the real Whales tab) so the two never drift apart; re-run this after
changing web/whales.js or the styles, and commit demo/."""
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEMO = ROOT / "demo"
REPO_URL = "https://github.com/Tanaka686/whale-accumulation-tracker"
API_URL = "https://www.coingecko.com/en/api?utm_source=vercel&utm_content=tanaka_l2"
DROP = ("saved_to", "elapsed_ms")
SENSITIVE = re.compile(r"[A-Za-z]:\|/Users/|/home/|\.env\b|api[_-]?key|x-cg-|CG-[A-Za-z0-9]{8,}|COINGECKO_", re.I)


def newest_virtual_30d() -> Path:
    best = None
    for f in sorted((ROOT / "data" / "whales").glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        if d.get("symbol") == "VIRTUAL" and d.get("days") == 30:
            best = f
    if not best:
        sys.exit("no VIRTUAL 30d scan found in data/whales/")
    return best


def clean(scan: dict) -> str:
    for k in DROP:
        scan.pop(k, None)
    text = json.dumps(scan, ensure_ascii=False, indent=1)
    bad = SENSITIVE.search(text)
    if bad:
        sys.exit(f"refusing to write the demo: found {bad.group(0)!r} in the scan")
    return text + "\n"


def demo_js() -> str:
    src = (ROOT / "web" / "whales.js").read_text(encoding="utf-8")
    marks = ["// ---------- formatting ----------", "// ---------- form ----------", "// ---------- results ----------", "// ---------- bring your own key ----------"]
    pos = [src.index(m) for m in marks]  # raises if a marker was renamed
    start = src.index("(() => {")
    boot = '''  // ---------- demo boot: one saved scan, no server, no key ----------
  const DEMO_REPO = "%s", DEMO_API = "%s";
  async function boot() {
    const box = $("#w-results");
    try {
      const r = await fetch("scan.json");
      if (!r.ok) throw new Error(r.status);
      S.data = await r.json();
    } catch (e) { box.innerHTML = '<div class="card w-error"><b>Could not load the saved scan.</b></div>'; return; }
    const when = new Date(S.data.scanned_at);
    const day = Number.isNaN(when.getTime()) ? "" : when.toLocaleDateString("en", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" });
    $("#demo-banner").innerHTML = `<b>Snapshot from ${esc(day)}.</b> Run the tool yourself to scan any token. <a href="${DEMO_REPO}" target="_blank" rel="noopener">GitHub repo ↗</a> <a href="${DEMO_API}" target="_blank" rel="noopener">CoinGecko API ↗</a>`;
    render();
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot); else boot();
})();
''' % (REPO_URL, API_URL)
    head = "/* Generated by scripts/build_demo.py from web/whales.js. Do not edit by hand. Read-only: renders one saved scan. */\n"
    return head + src[start:pos[0]] + src[pos[0]:pos[1]] + src[pos[2]:pos[3]] + boot


INDEX = '''<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Whale Accumulation Tracker · Demo</title>
<meta name="description" content="Read-only snapshot of a Whale Accumulation Tracker scan, powered by CoinGecko API.">
<link rel="stylesheet" href="/core-web/theme.css"><link rel="stylesheet" href="/static/styles.css"><link rel="stylesheet" href="/static/follow-overrides.css"><link rel="stylesheet" href="/static/whales.css">
<style>.demo-banner{margin:0 0 16px;padding:12px 16px;border:1px solid var(--cg-green);border-radius:var(--radius-md);background:var(--bg-elevated);line-height:1.6}.demo-banner a{margin-left:12px;white-space:nowrap;color:var(--cg-green);font-weight:700}.demo-top{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-bottom:16px}.demo-top h1{margin:0;font-size:22px}</style>
</head>
<body><div class="app-shell">
<div class="demo-top"><a href="%(api)s" target="_blank" rel="noopener"><img src="/brand/coingecko-api-on-dark.svg" alt="Data powered by CoinGecko API" height="32"></a><h1>Whale Accumulation Tracker</h1></div>
<div class="demo-banner" id="demo-banner" role="note"><b>Snapshot.</b> Run the tool yourself to scan any token. <a href="%(repo)s" target="_blank" rel="noopener">GitHub repo ↗</a> <a href="%(api)s" target="_blank" rel="noopener">CoinGecko API ↗</a></div>
<section id="panel-whales" class="panel active">
  <div id="w-results"><noscript>This demo needs JavaScript to draw the saved scan.</noscript></div>
  <p class="w-footnote">Holders, trades, transfers and prices come from CoinGecko API. Stance labels, reasons and the flow breakdown are computed by this tool, not CoinGecko fields, and are not financial advice.</p>
</section>
</div>
<script src="demo.js"></script></body></html>
''' % {"api": API_URL, "repo": REPO_URL}


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else newest_virtual_30d()
    scan = json.loads(src.read_text(encoding="utf-8"))
    DEMO.mkdir(exist_ok=True)
    (DEMO / "scan.json").write_text(clean(scan), encoding="utf-8", newline="\n")
    (DEMO / "demo.js").write_text(demo_js(), encoding="utf-8", newline="\n")
    (DEMO / "index.html").write_text(INDEX, encoding="utf-8", newline="\n")
    for src_dir, dst in ((ROOT / "core" / "web" / "theme.css", "core-web"), (ROOT / "web" / "styles.css", "static"), (ROOT / "web" / "follow-overrides.css", "static"), (ROOT / "web" / "whales.css", "static")):
        (DEMO / dst).mkdir(exist_ok=True)
        shutil.copyfile(src_dir, DEMO / dst / src_dir.name)
    (DEMO / "brand").mkdir(exist_ok=True)
    shutil.copyfile(ROOT / "core" / "brand" / "coingecko-api-on-dark.svg", DEMO / "brand" / "coingecko-api-on-dark.svg")
    print(f"demo built from {src.name} ({scan['symbol']} {scan['days']}d, scanned {scan['scanned_at']})")


if __name__ == "__main__":
    main()
